### PR TITLE
Vics Doc-build Fixes, Part 1 of issue #6480

### PR DESCRIPTION
**Pull request by vwheeler63**
### Description of the feature or fix

fix(docbuild): `@file` command arg mismatches

Fix Doxygen warnings where `@file` command had an argument
that was not an existing filename in the LVGL library. All of these
appear to have been the result of renaming the files but the
Doxygen `@file` command arguments were overlooked.

Fixes part of issue lvgl#6480.

Ready for review.

Note to Kevin @kdschlosser : Gabor wanted to keep the PR to the lvgl/lvgl repository small (~20-ish files per PR) so as to avoid conflicts as much as possible. So I am submitting these in small chunks of related changes. Be aware that I created a branch off documentation-fixes branch called fix/vics_docbild_fixes to submit my changes from. I've directed the PR to be "aimed" at your documentation-fixes branch.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by vwheeler63** [comment]
More results from documentation that was being omitted due to docstring errors:

Before:

image

After:

image

**Comment by kdschlosser** [comment]
do you want me to merge this code and you can open additional PR's for other changes?

**Comment by vwheeler63** [comment]
> do you want me to merge this code and you can open additional PR's for other changes?

@kdschlosser Hi, Kevin!  To clarify, I will copy a quote from Gabor's email to me:

> "... [for the errors described in your proposal], please send smaller PRs else we will continuously get merge conflicts while something gets merged. Let's target ~20 files per PR."

So my understanding is that that quantity of files (i.e. small numbers) is what HE wants to see in the PRs submitted to HIM.  So I believe that is correct that it should but submitted to `lvgl/lvgl` repository as a separate PR (provided you approve of its contents).  (See also the conversation under issue lvgl#6480:  Gabor is giving me some feedback and lengthening my "leash" for correcting things that are obvious that I see as I go forward.)

**Comment by vwheeler63** [comment]
@kdschlosser 

Hi, Kevin.

I added another commit to my `fix/vics_docbuild_fixes` branch, and it appears to have added the batch to this PR.  It appears it now involves 52 files instead of the original 26.  :-(

As I understand it (and I'm new at PRs so I may be wrong), you have to merge this one into your `documentation-fixes` branch and then take THAT branch and include IT in a PR to Gabor.  (?)

I scrambled to get THIS batch finished this evening in hopes that you can get the next PR submitted to Gabor (since you seem to be a night owl).

My next steps are going to be longer and involve around 3181 investigations of "is not documented" Doxygen warnings, so I will have to program some automation to make that practical.  I did the first 134 by manually viewing the warning list and simply progressing through it sequentially until the only ones left are "is not documented" warnings.

I am ending off for the day so text me if you need anything that is time critical.  :-)

--Vic

**Comment by kdschlosser** [comment]
You have separated by commit but not by PR. 

Submit your changes directly to LVGL if he wants them broken apart into separate PR's...

The real bitch about breaking it apart into different PR's is you are going to have to create a new branch off the master branch and make the changes and submit a PR and then make another branch off the master branch and again make another set of changes and submit a PR... If you make a branch and commit changes to that branch and then open a PR for those changes if you make any more commits to that branch they will automatically populate into the PR you made. It's a royal pain to do it the way that he wants it done but it's what you will have to do.

I said to make the PR's directly to LVGL because you are editing the header files. While I have made changes to the header files there shouldn't be too much to have to deal with in the way of merge conflicts if my PR gets merged before yours does or vice versa.

**Comment by vwheeler63** [comment]
@kdschlosser There is another solution that I can back out one commit, returning it to 26 files again, but then....  thinking this through....   Let me move this conversation to lvgl#6480 as Gabor must know a ton more about PRs than I do...

**Pull request closed without merging**
